### PR TITLE
feat: Add support for gp3 iops, throughput

### PR DESCRIPTION
**Pull request by MrMarkW**
*Issue #50*

*Description of changes:*

Add support for the following settings

* iops for gp3, io1, io2
* throughput for gp3
* min and max volume sizes when scaling
* maximum logical volume size
* maximum number of attached volumes

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by blajoie** [comment]
Added a few commits to @MrMarkW's PR, the code is now working well. Can we consider adding this in?

**Comment by MrMarkW** [comment]
@blajoie Thanks for the changes.  I'm not currently working a project related to this at the moment, but would love to help you push it through.

**Comment by rpmcginty** [comment]
@wleepang spam alert

1. Could we have help in reviewing/merging this change?
2. What would be the expected timeline for creating a `2.4.7` release?

**Review by wleepang — APPROVED** [review]
lgtm

**Comment by wleepang** [comment]
Merged - Thanks for the feature additions!

**Comment by microbioticajon** [comment]
Great that it is in the main branch (thanks to all involved!) - is there any chance this could be formally released?? /:-)

**Comment by blajoie** [comment]
yes please cut a fresh tag+release if possible @wleepang ! many thanks !

**Comment by wleepang** [comment]
Released!

**Pull request merged**
